//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Account
    {
        public int Client_Account_Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public Nullable<int> Account_Id { get; set; }
        public string Account_Number { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Client Client { get; set; }
    }
}
